#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

hello() {
    echo Hello from taskfile
    echo args: "$1" "$2" "$3"
}

dev2() {
    npm run dev 2>&1 &
    npm run test:w 2>&1 &
}

build() {
    ng-packagr
    # mv src/lib.metadata.json dist
}

eslint_run() {
    eslint src --ext ts
}

eslint_watch() {
    eslint_run
    inotifywait_cmd=`watch_cmd`
    while true; do
        $inotifywait_cmd -r src && \
            eslint_run
    done
}

watch_cmd() {
    case `uname -o` in
        Linux)
            echo 'inotifywait'
        ;;
        Msys)
            echo 'inotifywait-win32.cmd'
        ;;
        *)
            echo 'inotifywait'
        ;;
    esac
}

"$@"
