#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

remark_run() {
    node -r ts-node/register/transpile-only node_modules/remark-cli/cli.js readme.md "$@"
}

remark_output() {
    remark_run --output
}

build() {
    ng-packagr
    # mv src/lib.metadata.json dist
}

eslint_run() {
    eslint src --ext ts,tsx
}

"$@"
